### ISSUE TITLE
Support for documentation reference

### ISSUE THREAD

**Issue by AlexanderSkrock** [matthias-petri/camunda-modeler-template-generator#70]
The json schema support to provide a documentation reference using `documentationRef`. It would be great if we could add this to the existing `Template` annotation.

If possible I would like to contribute on this.

Kind regards
Alexander Skrock

**Comment by sascha-hanss-76** [comment]
Can you give an example how this "documentationRef" should be used in detail in context of an element template?

**Comment by AlexanderSkrock** [comment]
According to the documentation it can be any url (see [Defining Templates](https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/)). At my company we use this field to have a shortcut in the Camunda Modeler to jump to our confluence page.

Kind regards
Alexander Skrock
